---
- name: Install php-fpm and deps 
  apt: name={{ item }} state=present
  with_items:
    - php
    - php-cli
    - php-fpm
    - php-json
    - php-mysql
    - php-zip
    - php-gd
    - php-mbstring
    - php-curl
    - php-xml
    - php-pear
    - php-bcmath
    - libphp-phpmailer
    - libphp-simplepie  

- name: Disable default pool
  command: mv /etc/php/7.4/fpm/pool.d/www.conf /etc/php/7.4/fpm/pool.d/www.disabled creates=/etc/php/7.4/fpm/pool.d/www.disabled
 
- name: Copy php-fpm configuration
  template: src=magento.conf dest=/etc/php/7.4/fpm/pool.d/

# - name: Copy mcrypt.ini to correct location
#   template: src=mcrypt.ini dest=/etc/php/mods-available/

# - name: Fix php-fpm for Ubuntu 13.10
#   command: phpenmod mcrypt
#   notify: restart php-fpm